### ISSUE TITLE
All ingredient quantities and measures must be normalized

### ISSUE THREAD

**Issue by b-tapia-morales** [b-tapia-morales/NutriFoods#22]
The rules for normalization must be as follows:

Regarding measures:
- All Unicode characters must be replaced by their respective fraction representation. See [here](https://www.compart.com/en/unicode/decomposition/%3Cfraction%3E) for reference.
- If a quantity only has an integer part ⇾ Integer part must be the actual quantity of said ingredient, the numerator must be 0, and the denominator must be 1. Avoid using 0 as the denominator at all costs.
  - E.g.: 2 Tomatoes ⇾ {Integer part = 2, Numerator = 0, Denominator = 1}
- If a quantity has no integer part ⇾ Integer part must be 0, the numerator and denominator must represent the actual quantity of said ingredient.
  - E.g.: 1/2 Tablespoons of sugar ⇾ {Integer part = 0, Numerator = 1, Denominator = 2}
- If a quantity has both an integer and fractional part ⇾ Represent it as such. Self-explanatory.
- All measure names must be used in **singular** form instead of plural.
  - E.g.: 3 dashes of black pepper → 3, dash, black pepper → 3, pizca, pimienta negra.
  - E.g.: 2 tablespoons of vinegar → 2, tsp, vinegar → 2, cucharadita, vinagre.
- Be consistent. There must be only one way of representing a known measure. A cucharadita (teaspoon) must always be represented as such, and not as *Cdta*, *Cdta.*, or others. Pick the measure that makes the most sense in the context of the application, but you must always be consistent.

Regarding quantities in grams:
- The only measure unit that must be used to identify a quantity is the gram. It must be represented by the letter **g**. That means that all references in *gramos*, *gr*, *grs* and even measure units of a superior order like **kg** must also be replaced, provided that they were down scaled to **g** using the appropriate mathematical procedure.
  - In case it's impractical to convert *kg* to **g** directly, use *kg* as the standard unit. Do not use other variants like **kilo** or **kilos** instead.
- Decimal quantities must be checked in a case by case basis. Provided that some inconsistencies do occur when web scrapping the content from the original source, try to convert to fractional measures **only if it's what makes the most sense**.
  - E.g.: Source says It's using *1.5 cups of flour*. It's most likely a mistake of the source. Convert it to a fractional part as such → 1 1/2, cup, flour → 1 1/2, taza, harina.
  - E.g.: Source says it's using 250.4 g of red meat. We know it's not a mistake made by the source. We don't care about the decimal part. Don't include it.

Regarding quantities with no associated unit:
- This should be handled in a separate issue, as we need default measures for certain ingredients like apples or lettuces that are countable by themselves, and as such, can be used without a unit. Just follow the naming scheme below, and it should be fine enough for now.

Regarding the ingredient naming scheme:
- Countable ingredients must be in singular form (Apple, Orange, Potato, etc.).
- Non-countable ingredients must also be in singular form (Rice, Pasta, etc.).
- Countable ingredients for whose it doesn't make a lot of sense to refer to as countable, must be in plural form (you can count almonds or beans, but you normally don't refer to either of them as, for example, 20 almonds or 30 beans. It's always associated to kitchen measures).

Please do report all special cases for whose there isn't a clearly delimited way of handling them yet. And use your own personal judgement whenever necessary.

**Comment by EduardoPalma** [comment]
Question for the following cases.

x,x,ingredient => x,unit,ingredient

leave it as is?

1 1/2,Kg,ingredient => 1 1/2,grams,ingredient

I leave it as in this example case, or I transform them according to the units that should correspond to it, like the following.

1 1/2,kg,ingredient => 1500,gr,ingredient

PD: my inglesh is very bad 👍

**Comment by b-tapia-morales** [comment]
For ingredient names (Aceite de Oliva), include the "de".

For ingredients that are expressed in _kg_, leave it expressed in _g_, but not in _gr_ or _grams_.

For ingredients that are expressed in only units with no measures associated to it, leave it as, for example, "1, unidad, manzana". You must express only express "unidad" in singular form and not in plural form. You must be consistent and apply it everywhere else the same way.

**Comment by EduardoPalma** [comment]
Now for the names of the files with their normalized data

The names of these files will be as follows

1) ensaladaDeAtun.csv
2) ensalada_de_atun.csv
3) id_asociada.csv (for this case for each recipe we would have to assign an id to insert them in the database)

It should be said that the above files are with extension txt

**Comment by b-tapia-morales** [comment]
Some thoughts:

1. Associating the files to the name of the recipe means that there is a strict dependence to how they are originally named in the source. This is what makes the most sense to me. Provided that the source itself doesn't change these names, there shouldn't be an issue.
2. Associating the files to the ID's that our application uses means there is a strict dependence between the recipes and the order in which they are inserted. The order itself most likely depends on the order in which they were scrapped from the sites, which has no reason to stay the same everytime it is performed. I don't like that way of doing it as much as the other one.

Whether to use CamelCase or snake_case for the file naming, I think Snake case would be much safer to use, since we might need to extract the original recipe name at some point, and that is much, much harder to perform when using CamelCase. Just one thing to look out for: be **very, very careful** with the use (or lack thereof) of Uppercase when naming these files. It's possible that attempting to open the files "Ensalada_de_atun.csv" and "ensalada_de_atun.csv" might yield different results.
