### ISSUE TITLE
Genetic algorithms refactoring

### ISSUE THREAD

**Issue by b-tapia-morales** [b-tapia-morales/NutriFoods#27]
The genetic algorithms refactoring must be refactored according to the following rules:

- It must implement an interface, called ```IGeneticAlgorithm```, that declares the following methods:
```
CalculatePopulationFitness()
GenerateInitialPopulation()
Selection()
Crossover()
Mutation()
UpdatePopulationFitness()
SolutionExists()
```
**NOTE**: These methods will most likely take parameters from the main method as needed. They have been omitted just for demonstration purposes only.
- The main method is the one that finds the actual solutions, which is:
```
GenerateSolutions()
```
...and it must take the following arguments:
```
recipesAmount: int
energyTotal: double
carbohydratesPercentage: double
lipidsPercentage: double
proteinsPercentage: double
mealType: an enum that indicates the meal of the day for the regime that is being generated
```
- The algorithm must have a constructor that creates an instance of the ```IRecipeRepository``` by dependency injection. This repository will be used to make the queries to retrieve the recipes that are part of the total population to generate the regime.
- ALL methods that are declared by the implementing class of the ```IGeneticAlgorithm```, but not strictly defined by the interface itself, must be declared as PRIVATE.
- The implementing class must manipulate lists internally to generate the regimes. They must be created as ```private static readonly``` types, and they CANNOT be exposed externally from the implementing class. Prefer using ```ICollection``` instead of lists for them.
**NOTE**: To use these static collections properly, they must be initialized statically, and every time the main method is called, the lists must be cleared of the elements that were contained in them in previous calls.
- The main method must return a collection of recipes of the type ```MealMenuDto```. Strongly recommended using the aforementioned class to create the solutions instead of using an intermediate class as a "carrier" to convert them back to the desired class type.

**Comment by EduardoPalma** [comment]
I have a problem I have a static variable that will contain all the recipes inside the database, but I cannot initialize it with dependency injection

- Variable -> `private static readonly ICollection<MealMenuRecipeDto> _totalRecipes = null!;`

I have the method to perform the initialization, which is as follows:

```
 private IEnumerable<MealMenuRecipeDto> GetUniverseRecipes()
{
     return _repository.FindAll().Result.Select(r => new MealMenuRecipeDto() {Recipe = r, Quantity = 1}).ToList();
}
```

The question is, how do you get all the recipes, if the method is done in static mode, it would have to depend on dependency injection to get them, which is not clear to me.

Another query, what object should be created to pass the constructor of the class, I pass an interface "IRecipeRepository" as a parameter, but what specific object should be initialized to obtain those recipes?

builder

```
public Regime(IRecipeRepository recipeRepository)
    {
        _repository = recipeRepository;
    }
```
What specific object is it? RecipeRepository? 
If so, it still needs to be initialized, also in that case, what objects should be created?

**Comment by b-tapia-morales** [comment]
You can create and initialize new lists inside the main method and pass them as references. That can't be done if the lists are declared as static.

Regarding the repository, it needs to be declared as ```IRecipeRepository```. The repository is instantiated when using dependency injection.

**Comment by b-tapia-morales** [comment]
Done. Code is sufficiently modular as it was initially envisioned.
